### ISSUE TITLE
Could you add support for older minecraft versions?

### ISSUE THREAD

**Issue by paj1s** [vincss/mcEmptyServerStopper#5]

**Comment by vincss** [comment]
Hi !
Can you specify your use case (versions, java, minecraft) ?

**Comment by paj1s** [comment]
Sure, i tried it on java 8, paper 1.13.2. I can provide part of the log:
[00:52:54] [Server thread/ERROR]: Could not load 'plugins/EmptyServerStopper.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.15
	at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:226) ~[patched_1.13.2.jar:git-Paper-657]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-657]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[patched_1.13.2.jar:git-Paper-657]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255) ~[patched_1.13.2.jar:git-Paper-657]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-657]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-657]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-657]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_331]

**Comment by vincss** [comment]
Ok, it's a pretty old one, I will have to make a new version for that.
I will keep your informed.

**Comment by vincss** [comment]
It's the minecraft version that is more recent in the package.

**Comment by paj1s** [comment]
But i see "unsupported API version 1.15" so i guess it's the mc version. Thank you for support i would be happy if it could work for older versions.

**Comment by vincss** [comment]
I made a new release 1.0.1 that should be compatible with 1.13. Can you give it a try ?
https://github.com/vincss/mcEmptyServerStopper/releases/tag/v1.0.1

**Comment by paj1s** [comment]
It works great, thank you!
